environment:
    DEBUG: "1"
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python33"
        - PYTHON: "C:\\Python34"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python36"
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python33-x64"
        - PYTHON: "C:\\Python34-x64"
        - PYTHON: "C:\\Python35-x64"
        - PYTHON: "C:\\Python36-x64"
branches:
    only:
        - master
install:
    - "%PYTHON%\\python.exe -m pip install pytest pytest-cov python-coveralls"
build: off
test_script:
    - "%PYTHON%\\python.exe -m pytest tests.py -v --cov . --cov-report term-missing"
on_success:
    - "%PYTHON%\\python.exe -c 'from coveralls import wear;exit(wear())'"
