language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
branches:
    only:
        - master
env:
    - DEBUG=1
before_script:
    - pip install pytest-cov python-coveralls
script:
    - py.test tests.py -v --cov . --cov-report term-missing
after_success:
    - coveralls
