language: python
python:
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - nightly
branches:
    only:
        - master
env:
    - DEBUG=1
before_script:
    - if [ $TRAVIS_PYTHON_VERSION == 2.7 -o $TRAVIS_PYTHON_VERSION == 3.5 ]; then pip install pytest-cov python-coveralls; fi
script:
    - if [ $TRAVIS_PYTHON_VERSION == 2.7 -o $TRAVIS_PYTHON_VERSION == 3.5 ]; then py.test tests.py -v --cov . --cov-report term-missing; else py.test tests.py -v; fi
after_success:
    - if [ $TRAVIS_PYTHON_VERSION == 2.7 -o $TRAVIS_PYTHON_VERSION == 3.5 ]; then coveralls; fi
