language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - nightly
branches:
    only:
        - master
env:
    - DEBUG=1
before_script:
    - pip install pytest-cov codecov
script:
    - py.test tests.py -v --cov . --cov-report term-missing
after_success:
    - codecov
